[monitor:///opt/splunkforwarder/var/log/journal_stream.log]
disabled = false
index = main
sourcetype = linux:journal

[script:///opt/splunkforwarder/etc/app/my_app/bin/journalctl.sh]
interval = 60
sourcetype = linux:auth:journal
index = auth

[monitor:///var/log/boot.log]
disabled = false

[monitor:///var/log/Xorg.0.log]
disabled = false
