[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = main 
sourcetype = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = 0
index = main
sourcetype = WinEventLog:Microsoft-Windows-PowerShell/Operational

[WinEventLog://Security]
disabled = 0
index = main
sourcetype = WinEventLog:Security

[WinEventLog://System]
disabled = 0
index = main
sourcetype = WinEventLog:System

[WinEventLog://Application]
disabled = 0
index = main
sourcetype = WinEventLog:Application
